version: "2.1"
services:
  file-uploader-server:
    container_name: file-uploader-server
    build:
      context: docker-product-server
      dockerfile: Dockerfile
    image: file-uploader:latest
    ports:
      - 8080:8080
    links:
      - "db:database"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - spring-cloud-network
  db:
    image: postgres
    container_name: file-uploader-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_uploader
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
volumes:
  pgdata: